<?php

/**
 * Table names from dms-ahi.sql (all lowercase).
 * Model class => MySQL table name
 */
return [
    'Actions' => 'actions',
    'AIPromptTemplates' => 'aiprompttemplates',
    'AllowFileExtensions' => 'allowfileextensions',
    'Categories' => 'categories',
    'Clients' => 'clients',
    'CompanyProfiles' => 'companyprofile',
    'CronJobLogs' => 'cronjoblogs',
    'DailyReminders' => 'dailyreminders',
    'DocumentAuditTrails' => 'documentaudittrails',
    'DocumentComments' => 'documentcomments',
    'DocumentMetaDatas' => 'documentmetadatas',
    'DocumentRolePermissions' => 'documentrolepermissions',
    'Documents' => 'documents',
    'DocumentShareableLink' => 'documentshareablelink',
    'DocumentSignature' => 'documentsignatures',
    'DocumentStatus' => 'documentstatus',
    'DocumentTokens' => 'documenttokens',
    'DocumentUserPermissions' => 'documentuserpermissions',
    'DocumentVersions' => 'documentversions',
    'DocumentWorkflow' => 'documentworkflow',
    'EmailLogAttachments' => 'emaillogattachments',
    'EmailLogs' => 'emaillogs',
    'EmailSMTPSettings' => 'emailsmtpsettings',
    'FileRequestDocuments' => 'filerequestdocuments',
    'FileRequests' => 'filerequests',
    'HalfYearlyReminders' => 'halfyearlyreminders',
    'Languages' => 'languages',
    'LoginAudit' => 'loginaudits',
    'OpenAIDocuments' => 'openaidocuments',
    'PageHelper' => 'pagehelper',
    'Pages' => 'pages',
    'ProposalCandidate' => 'proposalcandidates',
    'ProposalFileRequest' => 'proposalfilerequests',
    'ProposalFile' => 'proposalfiles',
    'ProposalFolder' => 'proposalfolders',
    'ProposalPost' => 'proposalposts',
    'QuarterlyReminders' => 'quarterlyreminders',
    'ReminderNotifications' => 'remindernotifications',
    'Reminders' => 'reminders',
    'ReminderSchedulers' => 'reminderschedulers',
    'ReminderUsers' => 'reminderusers',
    'RoleClaims' => 'roleclaims',
    'Roles' => 'roles',
    'SendEmails' => 'sendemails',
    'UserClaims' => 'userclaims',
    'UserNotifications' => 'usernotifications',
    'UserRoles' => 'userroles',
    'Users' => 'users',
    'WorkflowLog' => 'workflowlogs',
    'Workflow' => 'workflows',
    'WorkflowStep' => 'workflowsteps',
    'WorkflowTransitionRole' => 'workflowtransitionroles',
    'WorkflowTransition' => 'workflowtransitions',
    'WorkflowTransitionUser' => 'workflowtransitionusers',
];
